import FeaturedSection from "./components/featuredSection";
import HeroSection from "./components/heroSection";

export default function Home() {
  return (
    <div>
  <div>
<HeroSection />
<FeaturedSection />
  </div>
 </div>
  );
}
export function generateMetadata(){
  return {
    title: "Dynamic Sanity CMS",
    description: "Generated BY M.Asif",
  }
}