import FeaturedSection from "./components/featuredSection";
import HeroSection from "./components/heroSection";

export function generateMetadata() {
  return {
    title: "Dynamic Sanity CMS",
    description: "Generated by M. Asif",
  };
}

export default function Home() {
  return (
    <div>
  <div>
<HeroSection />
<FeaturedSection />
  </div>
 </div>
  );
}
