import { urlFor } from "@/sanity/lib/image";
import Image from "next/image";
import Link from "next/link";
import PayButton from "@/app/components/PayButton";
import { client } from "@/sanity/lib/client";

// Metadata for the page
export function generateMetadata() {
  return {
    title: "Dynamic Sanity CMS",
    description: "Generated by M. Asif",
  };
}

// Revalidation time for ISR
export const revalidate = 60;


export default async function CarDetails({
  params: { details },
}: {
  params: { details: string };
}) {
  const query = `*[_type == "cars" && slug.current == $details][0]`;

 
  const car = await client.fetch(query, { details });

  if (!car) {
    return (
      <main>
        <section className="flex justify-center items-center bg-gray-200 min-h-screen">
          <div className="text-center">
            <h1 className="text-xl font-semibold text-red-600">
              Car details not found. Please check the URL or try again.
            </h1>
          </div>
        </section>
      </main>
    );
  }

  return (
    <main>
      <section className="flex justify-center items-center bg-slate-300">
        <div className="flex flex-col justify-center items-center w-full lg:w-8/12 lg:p-20">
          <h1 className="text-3xl font-semibold underline underline-offset-2 pb-10">
            {car.name} 2024 Price in Pakistan, Images, Reviews & Specs
          </h1>
          <div className="w-auto px-6">
            <Image
              src={urlFor(car.image).width(600).height(400).url()}
              alt={`Image of ${car.name}`}
              width={600}
              height={400}
              className="rounded-xl"
            />
          </div>
          <div className="flex flex-col justify-between text-xs p-10 lg:flex-row">
            <button className="px-4 py-3 mt-2 bg-blue-800 text-white border-2 border-blue-800 rounded-md mr-4">
              Book a Test drive
            </button>
            <button className="px-4 py-3 mt-2 bg-white text-blue-800 border-2 border-blue-800 rounded-md mr-4">
              Request Bank Finance
            </button>
            <button className="px-4 py-3 mt-2 bg-white text-blue-800 border-2 border-blue-800 rounded-md mr-4">
              Visit Place
            </button>
            <button className="px-4 py-3 mt-2 bg-white text-blue-800 border-2 border-blue-800 rounded-md mr-4">
              Car Inspection
            </button>
          </div>
          <h1 className="text-2xl font-medium items-center pb-10">
            Vehicle Description
          </h1>
          <div className="flex flex-wrap text-xs font-black w-full lg:pl-10">
            <ul className="flex flex-wrap">
              <li className="pr-2 mr-2">
                Numbers of Doors:{" "}
                <span className="font-normal">{car.doors}</span>
              </li>
              <li className="pr-2 mr-2">
                Engine: <span className="font-normal">{car.engine}</span>
              </li>
              <li className="pr-2 mr-2">
                Condition: <span className="font-normal">{car.condition}</span>
              </li>
              <li className="pr-2 mr-2">
                Driven: <span className="font-normal">{car.driven}</span>
              </li>
              <li className="pr-2 mr-2">
                Suspension Type:{" "}
                <span className="font-normal">{car.suspension}</span>
              </li>
              <li className="pr-2 mr-2">
                Avg Mileage: <span className="font-normal">{car.milage}</span>
              </li>
              <li className="pr-2 mr-2">
                Transmission:{" "}
                <span className="font-normal">{car.transmission}</span>
              </li>
              <li className="pr-2 mr-2">
                Fuel Type: <span className="font-normal">{car.fuel}</span>
              </li>
            </ul>
          </div>
          <h1 className="text-green-600 text-2xl font-semibold pt-10">
            PKR {car.price}
          </h1>
          <Link href="/form">
            <PayButton />
          </Link>
        </div>
      </section>
    </main>
  );
}

// Generating static paths for cars
export const generateStaticParams = async () => {
  const query = `*[_type == 'cars']{
    "slug": slug.current
  }`;

  const slugs = await client.fetch(query);

  return slugs.map((car: { slug: string }) => ({
    details: car.slug,
  }));
};
